In [1]:
import numpy as np

In [95]:
def mySweep(B,m):
    ## include square matrix check
    A = np.copy(B)
    n, c = A.shape
    if n==c:
        for k in range(m):
            if abs(A[k,k])>1e-8:
                for i in range(n):
                    for j in range(n):
                        if i != k and j != k:
                            A[i,j] = A[i,j]-A[i,k]*A[k,j]/A[k,k]
        
                for i in range(n):
                    if (i!= k):
                        A[i,k] = A[i,k]/A[k,k]
        
                for j in range(n):
                    if j!= k:
                        A[k,j] = A[k,j]/A[k,k]
        
                A[k,k] = -1/A[k,k]
            
            else:
                print "Warning: Not invertible"
                A = []
                break
                
        return A
    else:
        return "Warning: Not square matrix"
                

In [85]:
def myGaussGordan_vec(A,m):
    ## check square and invertible
    n,c = A.shape
    if n==c:
        B = np.hstack((A.copy(),np.identity(n)))
    
        for k in range(m):
            a = B[k,k]
            if abs(a) >= 1e-8:
                B[k,] = B[k,]/a
                for i in range(n):
                    if i!= k:
                        b = B[i,k]
                        B[i,:] = B[i,:]-B[k,:]*b
            elif abs(a) < 1e-8:
                print "Warning: Non-invertable"
                B = []
                break
        return B 
    
    else:
        return "Not sqaure matrix!"

In [27]:
def myGaussGordan(A,m):
    n = A.shape[0]
    B = np.hstack((A.copy(),np.identity(n)))
    
    for k in range(m):
        a = B[k,k]
        for j in range(2*n):
            B[k,j] = B[k,j]/a
        
        for i in range(n):
            if i!=k:
                b = B[i,k]
                for j in range(2*n):
                    B[i,j] = B[i,j] - B[k,j]*b
    return B

In [81]:
A = np.array([[1,7,17],[2,11,21],[3,13,23]],dtype = float)

In [82]:
B = np.array([[2,7,17],[2,11,21]],dtype = float)

In [83]:
C = np.array([[2,6],[1,3]],dtype = float)

In [99]:
print mySweep(A,3)
print mySweep(B,2)
print mySweep(C,2)

print myGaussGordan_vec(A,3)
print myGaussGordan_vec(B,2)
print myGaussGordan_vec(C,2)


[[-1.    3.   -2.  ]
 [ 0.85 -1.4   0.65]
 [-0.35  0.4  -0.15]]
[]
[[ 1.    0.    0.    1.   -3.    2.  ]
 [-0.    1.    0.   -0.85  1.4  -0.65]
 [ 0.    0.    1.    0.35 -0.4   0.15]]
Not sqaure matrix!
[]
